backend:
  name: git-gateway
  branch: main

  commit_messages:
    create: ':pencil: Create “{{slug}}”'
    update: ':pencil: Update “{{slug}}”'
    delete: ':fire: Delete “{{slug}}”'
    uploadMedia: ':bento: Upload “{{path}}” [skip ci]'
    deleteMedia: ':fire: Delete “{{path}}” [skip ci]'

media_folder: content/assets
public_folder: /assets
locale: en
display_url: https://starter.marscollective.co
logo_url: https://starter.marscollective.co/logo.svg

collections:
  - name: posts
    label: Posts
    label_singular: post
    folder: content/blog
    create: true
    media_folder: ''
    public_folder: ''
    sortable_fields: [title, date]
    path: '{{slug}}/index'
    fields:
      - { label: key, name: key, widget: hidden, default: blog-post }
      - { label: Title, name: title, widget: string }
      - {
          label: Date,
          name: date,
          widget: datetime,
          format: YYYY-MM-DD HH:mm:ss,
        }
      - { label: Image, name: image, widget: image }
      - { label: Tags, name: tags, widget: list }
      - { label: Description, name: description, widget: text }
      - { label: Body, name: body, widget: markdown }

  - name: sections
    label: Sections
    media_folder: ''
    public_folder: ''
    sortable_fields: []
    files:
      - file: content/sections/contact/index.md
        label: Contact
        name: contact
        fields:
          - { label: key, name: key, widget: hidden, default: contact }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }

      - file: content/sections/not-found/index.md
        label: '404'
        name: not-found
        fields:
          - { label: key, name: key, widget: hidden, default: not-found-page }
          - { label: Title, name: title, widget: string }
          - { label: Message, name: message, widget: string }

  - name: settings
    label: Settings
    media_folder: ''
    public_folder: ''
    sortable_fields: []
    editor:
      preview: false
    files:
      - file: README.md
        label: README
        name: readme
        fields:
          - { label: Body, name: body, widget: markdown }

      - file: content/settings/siteMetadata.json
        label: Metadata
        name: siteMetadata
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Short Title, name: shortTitle, widget: string }
          - { label: Description, name: description, widget: text }
          - { label: Site URL, name: siteUrl, widget: string }
          - { label: Favicon, name: favicon, widget: image }
          - { label: Background Color, name: backgroundColor, widget: string }
          - { label: Theme Color, name: themeColor, widget: string }
          - { label: Lang, name: lang, widget: string }
          - { label: GTM ID, name: gtmID, widget: string }
          - label: Social Links
            label_singular: profile
            name: socialLinks
            widget: list
            fields:
              - {
                  label: Label,
                  name: label,
                  widget: select,
                  options:
                    [Email, Facebook, Instagram, Messenger, Twitter, WhatsApp],
                }

              - { label: URL, name: url, widget: string }
